<%@ Page Language="C#" MasterPageFile="~/Admin/adminMain.Master" AutoEventWireup="true" CodeBehind="adminAuthors.aspx.cs" Inherits="TihBlogCompact.Admin.adminAuthor" ValidateRequest="false" %>
<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>

<asp:Content ID="_mainContent" ContentPlaceHolderID="_mainContentPlaceHolder" runat="server">
  <div class="subMenu">
   &nbsp;<a class="subMenu_link" href="adminMain.aspx"><%= Resources.Resources.Main %></a>
  </div>
  <div style="border-width:0px;" class="article_title">
    <%= Resources.Resources.Authors %>
  </div>
  <div style="margin-top:15px;">
   <asp:GridView ID="_authorsGV" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" SkinID="AdminGridSkin"
          DataSourceID="_authorsDS" AutoGenerateDeleteButton="false" AutoGenerateEditButton="true">
     <Columns>
       <asp:BoundField DataField="names" HeaderText="names" SortExpression="names" />
       <asp:TemplateField HeaderText="CV">
         <ItemTemplate>
           <%# DataBinder.Eval(Container.DataItem, "resume") %>
         </ItemTemplate>
         <EditItemTemplate>
           <FCKeditorV2:FCKeditor ID="_fckEditor" Width="500px" Height="350px" 
            ToolbarSet="TihBlogAdmin" ToolbarCanCollapse="false" runat="server" Value="<%# Bind('resume') %>"
            BasePath="~/editor/" />
         </EditItemTemplate>
       </asp:TemplateField>
       <asp:TemplateField HeaderText="Picture">
         <ItemTemplate>
          <asp:Image ID="_viewAuthorImage" runat="server" ImageUrl='<%# DataBinder.Eval(Container.DataItem, "pictureURL") %>' />
         </ItemTemplate>
         <EditItemTemplate>
           <asp:DropDownList ID="_picturesDDL" runat="server"
              OnInit="_picturesDDL_Init" AutoPostBack="true"
              OnSelectedIndexChanged="_picturesDDL_SelectedIndexChanged" />
           <asp:Image ID="_previewAuthorImage" runat="server" ImageUrl='<%# Bind("pictureURL") %>'></asp:Image>
         </EditItemTemplate>
       </asp:TemplateField>
     </Columns>
   </asp:GridView>
   <tasp:TBAccessDataSource ID="_authorsDS" runat="server"
          SelectCommand="SELECT [ID], 
                                [names], 
                                [resume],
                                [pictureURL]
                         FROM [Authors]"
          UpdateCommand="UPDATE [Authors]
                         SET [names]=@names, 
                             [resume]=@resume,
                             [pictureURL]=@pictureURL
                         WHERE [ID]=@ID">
      <UpdateParameters>
        <asp:Parameter Name="names" Type="String" />
        <asp:Parameter Name="resume" Type="String" />
        <asp:Parameter Name="pictureURL" Type="String" />
        <asp:Parameter Name="ID" Type="Int64" />
      </UpdateParameters>
   </tasp:TBAccessDataSource> 
  </div>
</asp:Content>
